global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-f5-big-ip-virtual-edition
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-f5-big-ip-virtual-editiont1:
    parameter_input: quickstart-f5-big-ip-virtual-edition-example-params1.json
    template_file: quickstart-f5-big-ip-virtual-edition-example1.template
  quickstart-f5-big-ip-virtual-editiont2:
    parameter_input: quickstart-f5-big-ip-virtual-edition-example-params2.json
    template_file: quickstart-f5-big-ip-virtual-edition-example2.template
